image: registry.gitlab.com/tiltmesenpai/kicad-nightly-runner/kicad-nightly-runner:20202606

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_gerbers:
  script: 
  - export PCB_VERSION=$(git describe --tags)
  - export PCB_PATH=hub75_poe.kicad_pcb
  - /usr/bin/plot_gerbers.py
  artifacts:
    paths:
    - plot
